services:
  caldera_reporter:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_TOKEN
      - CALDERA_SERVER
      - REACT_APP_API_SERVER
      - REACT_APP_API_SERVER_PORT
      - REACT_APP_DEPLOYMENT
      - ADVERSARY_ID
    expose:
      - "5005"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      caldera_reporter:
        condition: service_healthy
    restart: on-failure